### ISSUE TITLE
CSS leaks onto page. 

### ISSUE THREAD

**Issue by TheFirstLairron** [nheath99/BlazorNodaTimeDateTimePicker#35]
The CSS that you have written for buttons in this control is not done in a way that isolates your styles to the control. Including the control on a page was enough to remove all default styling from the rest of the buttons on the page. Maybe consider pseudo-namespacing of your CSS selectors?

PS: I may even be willing to help out with this in the next few days if you are interested.

**Comment by nheath99** [comment]
TODO: remove button styling in https://github.com/nheath99/BlazorNodaTimeDateTimePicker/blob/master/src/BlazorNodaTimeDateTimePicker/content/variables.scss - add class (e.g. "datetimepicker-button")

**Comment by nheath99** [comment]
Thanks - feel free to pick up anything you think could be improved. Not actively developing this yet as Blazor is still experimental, and I don't think UI components lend themselves nicely to Razor Components (sending a request to the server to change the displayed month seems silly...), but I think it could be very useful if/when Blazor on wasm is released.
