### ISSUE TITLE
RENAME PROJECT - suggestions wanted

### ISSUE THREAD

**Issue by nheath99** [nheath99/BlazorNodaTimeDateTimePicker#41]
It's clear that "Blazor" is being dropped in favour of "Razor Components", and I think BlazorNodaTimeDateTimePicker is a bit too long as the root namespace. A few suggestions to change the name of the project:
- NodaTimePicker
- NodaTimeDateTimePicker
- BlazorNodaTimePicker

Please feel free to suggest any others below!

**Comment by AmarjeetBanwait** [comment]
Now as "Razor Components" is being dropped. I think it should be straight forward as "BlazorDatePicker" and "NODA" can be put into description.

**Comment by nheath99** [comment]
Of course they changed their mind - Blazor is such a cool name I'm glad they kept it! Will be renaming this project NodaTimePicker as it's more succinct.
