### ISSUE TITLE
TimePicker cannot be bound?

### ISSUE THREAD

**Issue by digitaldias** [nheath99/BlazorNodaTimeDateTimePicker#96]
I can't find a way to start the time picker with an existing LocalTime Value. Perhaps this is not yet supported? Even on the demo site, the TimePicker starts at 00:00

**Comment by nheath99** [comment]
Hi, you just need to bind the ````SelectedTime```` property of the ````TimePicker```` to the relevant LocalTime variable. I've added a demonstration to the dev branch:
 https://github.com/nheath99/NodaTimePicker/blob/861ac1d31759b84e3cda162d6bc0149a7c5aacf7/src/NodaTimePicker.Demo/Pages/TimePickerDemo.razor#L30

You can then set the value of ````selectedTime4```` in the page code, such as:

https://github.com/nheath99/NodaTimePicker/blob/861ac1d31759b84e3cda162d6bc0149a7c5aacf7/src/NodaTimePicker.Demo/Pages/TimePickerDemo.razor#L95

**Comment by digitaldias** [comment]
Perfect! Thanks for the reply and the updated example! I'll close this issue :)
