### ISSUE TITLE
Weird and unusable layout for DatePicker

### ISSUE THREAD

**Issue by sroy2020** [nheath99/BlazorNodaTimeDateTimePicker#99]
Hi,

When using a DatePicker I get a very weird and unusable layout. See attached screenshot.
Here's the code using NodaTimePicker 0.7.0. The code is very similar to the one in Index.razor (project NodaTimePicker.Demo). I'm using Blazor 3.2.0-preview3.20168.3 and Bootstrap v4.4.1.

Please let me know if I'm missing something or it's an issue.
Thanks

```
@using NodaTime
@using NodaTimePicker

    <div class="rectangle">
        <input type="text" @onfocus=@Focused value=@_selectedDate
               class="form-control mb-2" placeholder="Focus to open DatePicker..." />
        <DatePicker Visible=@_datePickerVisible OnSelected=@Selected ShowClose=@true />
    </div>


@code {
    private bool _datePickerVisible = false;
    private LocalDate? _selectedDate;

    private void Focused(EventArgs e)
    {
        _datePickerVisible = true;
    }

    private void Selected(LocalDate localDate)
    {
        _selectedDate = localDate;
        _datePickerVisible = false;
        StateHasChanged();
    }
}

```
Parents div are mainly using CSS class container-fluid, row and col. Nothing fancy.

Additional CSS
```
/* For visual debugging only */
.rectangle {
    border: 1px solid orange;
    margin: 1px;
}
```

![WeirdLayout](https://user-images.githubusercontent.com/61807678/80719855-0fb88800-8aca-11ea-844e-035e74d66626.png)

**Comment by nheath99** [comment]
Hi, it looks like you are not referencing the .css file from the library.

See this example: https://github.com/nheath99/NodaTimePicker/blob/caaa2fa0925e403b9f8c4837eac9efd3d6cd5d12/src/NodaTimePicker.Demo/wwwroot/index.html#L11

**Comment by sroy2020** [comment]
Hi,

I did not test it but I assume that's what I was missing.

Thanks
